### ISSUE TITLE
Error [parser.cc:701] Error finding file [panda] | Error Code 1: Msg: Unable to read file:panda

### ISSUE THREAD

**Issue by liushuya7** [AndrejOrsula/panda_ign_moveit2#16]
Hi,

While launching ignition, simulator can't load the panda robot model. 

`ros2 launch panda_description view_ign.launch.py`

Output:

```bash
[ign gazebo-1] Error [parser.cc:701] Error finding file [panda].
[ign gazebo-1] [Err] [UserCommands.cc:998] Error Code 1: Msg: Unable to read file:panda
...
[rviz2-5] [ERROR] [1643904244.369392818] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
...
[move_group-3] [ERROR] [1643904255.757169280] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Action client not connected: joint_trajectory_controller/follow_joint_trajectory
[move_group-3] [ERROR] [1643904270.774255338] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Action client not connected: gripper_trajectory_controller/follow_joint_trajectory
```
Is there anything else that I need to configure?

**Comment by AndrejOrsula** [comment]
Hello @liushuya7,

As mentioned under [panda_description/README.md](https://github.com/AndrejOrsula/panda_ign_moveit2/blob/master/panda_description/README.md), you might need to export `IGN_GAZEBO_RESOURCE_PATH` as such:
```bash
export IGN_GAZEBO_RESOURCE_PATH=${REPO_DIR}/panda_description${IGN_GAZEBO_RESOURCE_PATH:+:${IGN_GAZEBO_RESOURCE_PATH}}
```
You could do it inside your setup script if that's more convenient. 

If that is not the issue, try manually executing [.git_hooks/pre-commit_convert_xacros.bash](https://github.com/AndrejOrsula/panda_ign_moveit2/blob/master/.git_hooks/pre-commit_convert_xacros.bash) to trigger URDF/SDF/SRDF generation.

Hope this helps.

**Comment by 0smile** [comment]
Hi @AndrejOrsula, could you tell me how to replace the content in {REPO_DIR}? I tried to replaced it with the direct path to panda_description but result no good. Thank you!

**Comment by AndrejOrsula** [comment]
Hello @0smile, `${REPO_DIR}` should be the directory path to this repository, i.e. wherever you cloned `panda_ign_moveit2` repository. In this way, `${IGN_GAZEBO_RESOURCE_PATH}` will point to the `panda_description` package that contains the `panda` SDF model.

**Comment by 0smile** [comment]
> Hello @0smile, `${REPO_DIR}` should be the directory path to this repository, i.e. wherever you cloned `panda_ign_moveit2` repository. In this way, `${IGN_GAZEBO_RESOURCE_PATH}` will point to the `panda_description` package that contains the `panda` SDF model.

It works! Thanks a lot!
