### ISSUE TITLE
Absolute path in model.sdf causes problems

### ISSUE THREAD

**Issue by marc-wittwer** [AndrejOrsula/panda_ign_moveit2#20]
Hi @AndrejOrsula 
Since there is an absolute path in the model.sdf file, the file does not resolve correctly on my machine.

https://github.com/AndrejOrsula/panda_ign_moveit2/blob/ed4bbd3d27e7d487a3109a130301802ac9a338b4/panda_description/panda/model.sdf#L731

**Comment by AndrejOrsula** [comment]
Hello @marc-wittwer,

Please run [`xacro2sdf.bash`](https://github.com/AndrejOrsula/panda_ign_moveit2/blob/master/panda_description/scripts/xacro2sdf.bash) as mentioned in [panda_description/README.md](https://github.com/AndrejOrsula/panda_ign_moveit2/blob/master/panda_description/README.md#sdf).

Alternatively, run [`.git_hooks/pre-commit_convert_xacros.bash`](https://github.com/AndrejOrsula/panda_ign_moveit2/blob/master/.git_hooks/pre-commit_convert_xacros.bash), which makes sure that URDF and SRDF are also updated (both should be fine though).

**Comment by marc-wittwer** [comment]
Thanks. I did miss that step.
