### ISSUE TITLE
Using load_yaml() directly is deprecated.

### ISSUE THREAD

**Issue by stelmik** [AndrejOrsula/panda_ign_moveit2#23]
https://github.com/AndrejOrsula/panda_ign_moveit2/blob/5679c0a97d5e34199271ed7abf02cf303d0e8fb9/panda_description/urdf/panda.ros2_control#L21

I think it should be change to:

```xml
<xacro:property name="initial_positions" value="${xacro.load_yaml(initial_positions_file)['initial_joint_positions']['panda_arm']}"/>
```

because of warnings:
`Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.`

**Comment by stelmik** [comment]
The same in line:
https://github.com/AndrejOrsula/panda_ign_moveit2/blob/5679c0a97d5e34199271ed7abf02cf303d0e8fb9/panda_description/urdf/panda.ros2_control#L158

**Comment by AndrejOrsula** [comment]
Hello @stelmik,

Thank you for opening this issue.
I was unaware of this deprecation notice. Do you know when this deprecation was introduced?
This repository is currently targeted at `galactic` and I tested it around 4 months ago. Could you please let me know what ROS 2 distribution you are using?

**Comment by stelmik** [comment]
Hi, I'm using ROS 2 Humble on Ubuntu 22.04.
I think this is "new deprecation". I upgraded installed packages for ROS 2 Humble on Ubuntu last week and since then the message appears.
The execution of the program breaks because of message warnings.

**Comment by AndrejOrsula** [comment]
Yes, that's what I expected. I have not tested this repository with `humble` yet.

First, I need to check if this change would be breaking on `galactic` (and maybe even `foxy`). Unfortunately, I do not have time to do that right now.

**Comment by AndrejOrsula** [comment]
The deprecation notice related to `xacro.load_yaml()` introduced in `humble` is now addressed in the [`humble` branch](https://github.com/AndrejOrsula/panda_ign_moveit2/tree/humble) of this repository.

Relevant diff: https://github.com/AndrejOrsula/panda_ign_moveit2/commit/bae67153c39c130da46deaff88bc1351aff924c4#diff-0748b86797de50ba691ab84c5ff326e629870c1466ddee18f5c921148c76382aR21
