### ISSUE TITLE
gazebo Fortress vs gazebo 11

### ISSUE THREAD

**Issue by FrGe2016** [AndrejOrsula/panda_ign_moveit2#25]
Just a few question

My setup is with gazebo 11. Would the package work with it ?

If not, Can i have both gazebo 11 and gazebo 11 without using a docker or a virtual environment ?

**Comment by AndrejOrsula** [comment]
Hello,

No, this repository is not compatible with Gazebo *classic* 11. It is only functional with the *new* ~Ignition~ Gazebo, and it was last tested on Gazebo `fortress`.

Tutorials for Gazebo *Classic* can be found here: https://classic.gazebosim.org/tutorials
Tutorials for *new* Gazebo can be found here: https://gazebosim.org/docs

You should be able to install Gazebo 11 locally. Try checking the tutorials above.
